name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */1 * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout current repository to Master branches
        uses: actions/checkout@v1
      - name: Setup NodeJs 13.x
        uses: actions/setup-node@v1
        with: 
          node-version: '13.x'
      - name: Cache dependencies and build outputs to improve workflow execution timeZone
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.os}}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm Install
      - name: Generate README file
        run: node index.js
      - name: Commit and Push new README.md to the repository
        uses: Doro97/mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}